apiVersion: v1
kind: Service
metadata:
  labels:
    component: db
  name: db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    component: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: db
  name: lago-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: db
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_DB
              value: lago
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_USER
              value: lago
          image: postgres:14.0-alpine
          name: lago-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /data/postgres
              name: lago-postgres-data
      restartPolicy: Always
      volumes:
        - name: lago-postgres-data
          persistentVolumeClaim:
            claimName: lago-postgres-data

